- name: Install python.
  yum: 
    name: "{{ python_version }}"
    state: present


- name: Install python dev.
  yum: 
    name: "{{ python_package_dev_RedHat }}"
    state: present
  when: python_package_dev_RedHat is defined