- include_tasks: RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: Debian.yml
  when: ansible_distribution  == 'Debian'

- include_tasks: Ubuntu.yml
  when: ansible_distribution  == 'Ubuntu'