---
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Docker.
  package:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"

- name: Create /etc/docker.
  file:
    path: /etc/docker
    state: directory
    mode: 755

- name: "修改配置文件."
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json

- name: Ensure Docker is started and enabled at boot.
  systemd:
    daemon_reload: yes
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"

- include_tasks: docker-compose.yml
  when: docker_install_compose == 'yes'
  register: docker_compose
- debug:
    var: docker_compose

- include_tasks: docker-users.yml
  when: docker_users  | length > 0
